apiVersion: batch/v1
kind: Job
metadata:
  name: santander-anagrams.job
spec:
  template:
    spec:
      containers:
        -
          args: 
            - anagrams.py
          command:
            - python
          image: index.docker.io/ssanchezmingo/santander-anagrams:ci
          imagePullPolicy: IfNotPresent
          name: santander-anagrams-job-conteiner
          volumeMounts:
            - 
              mountPath: /data
              name: santander-anagrams-job-volume
              readOnly: true
      initContainers:
        -
          args:
            - -c
            - ' set -x ; cd /downloads ; rm -f ${filename} ; wget ${url}/${filename} '
          command:
            - sh
          env:
            -
              name: filename
              valueFrom:
                configMapKeyRef:
                  key: filename
                  name: santander-anagrams-job-cm
            -
              name: url
              valueFrom:
                secretKeyRef:
                  key: filename
                  name: santander-anagrams-job-secret

          image: busybox
          name: santander-anagrams-job-initcontainer
          volumeMounts:
            -
              mountPath: /downloads
              name: santander-anagrams-job-volume
              readOnly: false
      restartPolicy: Never
      volumes:
        -
          name: santander-anagrams-job-volume
          emptyDir: {}
status: {}
