name: ci
on:
  push:
    branches:
      - docker
jobs:
  Dockerfile:
    env:
      file: Dockerfile
      pattern: '{1: 0, 2: 80, 3: 805, 5: 4497, 4: 2790, 8: 4821, 7: 5759, 9: 3552, 6: 6246, 11: 1054, 10: 2082, 12: 558, 14: 140, 16: 70, 15: 90, 20: 6, 19: 14, 17: 44, 13: 250, 18: 20, 21: 8, 22: 4, 23: 0, 24: 0}'
      registry: index.docker.io
      repository: santander-anagrams
      sleep: 10
      tagname: ci
      user: ssanchezmingo
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/ckeckout@v2
      - name: build
        run: docker build --file ${file} --no-cache --tag ${registry}/${user}/${repository}:${tagname} .
      - name: run
        run:  docker run --detach --entrypoint python --name ${repository} ${registry}/${user}/${repository}:${tagname} anagrams.py
      - name: test
        run: while true ; do sleep ${sleep} ; docker logs ${repository} 2>& 1 | grep "${pattern}" && break ; done
